# Generated by Django 4.2.5 on 2023-10-04 13:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="blocks",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.RichTextBlock()),
                                (
                                    "cta",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(required=True),
                                            ),
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    help_text="Use this field to point to internal page."
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.URLBlock(
                                                    help_text="Use this field to point to an external page."
                                                ),
                                            ),
                                            (
                                                "isExternalLink",
                                                wagtail.blocks.BooleanBlock(
                                                    help_text="Make sure you mark this checkbox to improve performance."
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                default=None,
                use_json_field=True,
            ),
        ),
    ]
